steps:
  - name: 'maven:3-jdk-8'
    args:
      - package
    entrypoint: mvn
  - name: ubuntu
    args:
      - 'ls'
    timeout: 100s
  - name: ubuntu
    args:
      - echo
      - 'packaging done'
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/capgemini-sep/gaganapp
      - .
images:
  - gcr.io/capgemini-sep/gaganapp
